# Generated by Django 5.0.3 on 2024-04-22 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flow_manager", "0001_initial"),
    ]

    operations = []
